version: '3.7'

services:
    test_db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test_db
        volumes:
            - test_db:/var/lib/mysql
        ports:
            - 3307:3306
volumes:
    test_db:
